### PR TITLE
final changes including meta descriptions and no scripts

### PR DESCRIPTION
**Pull request by DavidKozdra**
should be linked to https://github.com/ry0y4n/ExifFrame/issues/26

most of the changes are explained there

added noscript tag as well and some other minor changes, did my best to add the original language but I used google translate so let me know if it is not accurate.

### CODE REVIEW

**Comment by ry0y4n** [comment]
@DavidKozdra 
Thanks for opening the PR!

Making the cursor a pointer is certainly a nice change!

However, there seem to be a few unnecessary new lines and changes to review the code. It would be very easy to review if the "Files changed" could be kept to a minimum. Thanks!

**Comment by DavidKozdra** [comment]
keep in mind Most of the changes are from new lines

**Comment by ry0y4n** [comment]
Ok, I will check later.

**Comment by DavidKozdra** [comment]
Hey just wanted to check in to clarify the line lengths should be almost the same 
the things I changed will really make your app better 
lang attribute will automatically translate the page in the native lang of the user
the noscript tag will assure that users that have js off will see a message reminding them to turn it on for this app 
the cursor pointer which will help all users understand they are buttons

**Comment by DavidKozdra** [comment]
Hey guys no rush just want to make sure this is seen

**Comment by ry0y4n** [comment]
@DavidKozdra Sorry for the long wait.

I have confirmed that this PR contains the following elements.

1. The cursor becomes a pointer when the button is hovered.
2. HTML language specification (for "ja")
3. Create description meta tag
4. no script tag setting
5. code refactoring (["]or['], add new ilne, etc...)

Please eliminate the 5.("code refactoring") from PR. Then this PR will be merged. (The code rules are being developed (not pushed) and I will refactor them myself as soon as the rules are finalized).

**Comment by ry0y4n** [comment]
I am now going to organize the meta-information on this site. Some of them may encompass or conflict with your PR.

**Comment by DavidKozdra** [comment]
Ok I will be available to fix them soon

**Comment by ry0y4n** [comment]
Since time has passed since the PR was opened and the code has been significantly updated, we will close the PR for now :bow:

**Comment by DavidKozdra** [comment]
Ok I will redo soon

**Pull request closed without merging**
